export default const dummy = {
  name: 'root',
  children: [
    {
      name: 'ao',
      children: [
        { name: 'Lekane', value: 364 },
        { name: 'Tile', value: 2482 },
        { name: 'Loomweight', value: 13 },
        { name: 'Jug', value: 532 },
        { name: 'Pithos', value: 712 },
        { name: 'Amphora', value: 2472 },
        { name: 'Undetermined', value: 5980 },
        { name: 'Closed shape', value: 2394 },
        { name: 'Cooking pot', value: 838 },
        { name: 'Open shape', value: 1720 },
        { name: 'Basin', value: 352 },
        { name: 'Bowl', value: 128 },
        { name: 'Skyphos', value: 163 },
        { name: 'Krater', value: 75 },
        { name: 'Kantharos', value: 16 },
        { name: 'Chytra', value: 38 },
        { name: 'Cup', value: 301 },
        { name: 'Juglet', value: 152 },
        { name: 'Louterion', value: 14 },
        { name: 'Grinding stone', value: 118 },
        { name: 'Plate', value: 38 },
        { name: 'Lamp', value: 59 },
        { name: 'Waster', value: 4 },
        { name: 'Hydria', value: 31 },
        { name: 'Table amphora', value: 73 },
        { name: 'Beehive', value: 90 },
        { name: 'Mortar', value: 127 },
        { name: 'Brasier', value: 3 },
        { name: 'Lekythos', value: 33 },
        { name: 'Kotyle', value: 44 },
        { name: 'Lid', value: 52 },
        { name: 'Stopper', value: 4 },
        { name: 'Lekanis', value: 23 },
        { name: 'Oinochoe', value: 38 },
        { name: 'Kylix', value: 44 },
        { name: 'Terracotta', value: 8 },
        { name: 'Amphora stopper', value: 1 },
        { name: 'Stone', value: 145 },
        { name: 'Stemless cup', value: 6 },
        { name: 'Slag', value: 18 },
        { name: 'Jar', value: 110 },
        { name: 'Brick', value: 44 },
        { name: 'Unguentarium', value: 3 },
        { name: 'Lagynos', value: 1 },
        { name: 'Saltcellar', value: 5 },
        { name: '', value: 2 },
        { name: 'Stand', value: 9 },
        { name: 'Shell', value: 39 },
        { name: 'Collared jar', value: 1 },
        { name: 'Pebble', value: 34 },
        { name: 'Pedestalled bowl', value: 7 },
        { name: 'Drinking vessel', value: 50 },
        { name: 'Olpe', value: 10 },
        { name: 'Mug', value: 3 },
        { name: 'Lopas', value: 12 },
        { name: 'Alabastron', value: 1 },
        { name: 'Funerary stele', value: 1 },
        { name: 'Cheese pot', value: 4 },
        { name: 'Lebes', value: 8 },
        { name: 'Aryballos', value: 4 },
        { name: 'Litharge', value: 3 },
        { name: 'Cistern lining', value: 6 },
        { name: 'Horseshoe', value: 1 },
        { name: 'Pyxis', value: 5 },
        { name: 'Stamnos', value: 1 },
        { name: 'Flake', value: 13 },
        { name: 'Bead', value: 1 },
        { name: 'Scraper', value: 1 },
        { name: 'Kados', value: 18 },
        { name: 'Scoop', value: 2 },
        { name: 'Pan', value: 9 },
        { name: 'Pessos', value: 7 },
        { name: 'Tripod', value: 3 },
        { name: 'Askos', value: 2 },
        { name: 'Antefix', value: 2 },
        { name: 'Griddle', value: 1 },
        { name: 'Loutrophoros', value: 1 },
        { name: 'Stemmed cup', value: 6 },
        { name: 'Cooking bell', value: 4 },
        { name: 'Tankard', value: 1 },
        { name: 'Exaleiptron', value: 2 },
        { name: 'Amphoriskos', value: 6 },
        { name: 'Storage vessel', value: 9 },
        { name: 'Skeleton', value: 2 },
        { name: 'Stemmed vessel', value: 2 },
        { name: 'Krateriskos', value: 2 },
        { name: 'Crushing stone', value: 1 },
        { name: 'Psykter', value: 1 },
        { name: 'Bolsal', value: 2 },
        { name: 'Spindle whorl', value: 1 },
        { name: 'Furnace base', value: 1 },
        { name: 'Pot', value: 2 },
        { name: 'Ashlar', value: 1 },
        { name: 'Crucible', value: 2 },
        { name: 'Sieve', value: 1 },
        { name: 'Dinos', value: 1 },
        { name: 'Trough', value: 1 },
        { name: 'Ladle', value: 1 },
        { name: 'Lopadion', value: 1 },
        { name: 'Stemmed bowl', value: 1 }
      ]
    }
  ]
};
